-- ==============================================================================
-- UPSC Master Syllabus SQL Seed
-- Total Subjects: 26 | Total Sections: 55 | Total Topics: 420
-- ==============================================================================

-- 1. SEED SYLLABUS SUBJECTS
insert into public.syllabus_subjects (id, name, exam, paper, display_order, active)
values
  ('subj-pre-hist', 'History of India & Indian National Movement', 'Prelims', 'General', 1, true),
  ('subj-pre-polity', 'Indian Polity & Governance', 'Prelims', 'General', 2, true),
  ('subj-pre-geo', 'Geography', 'Prelims', 'General', 3, true),
  ('subj-pre-eco', 'Indian Economy', 'Prelims', 'General', 4, true),
  ('subj-pre-env', 'Environment & Ecology', 'Prelims', 'General', 5, true),
  ('subj-pre-scitech', 'Science & Technology', 'Prelims', 'General', 6, true),
  ('subj-pre-ca', 'Current Affairs', 'Prelims', 'General', 7, true),
  ('subj-pre-csat', 'CSAT', 'Prelims', 'General', 8, true),
  ('subj-mains-gs1-culture', 'Indian Heritage & Culture', 'Mains', 'GS1', 101, true),
  ('subj-mains-gs1-history', 'Modern Indian History', 'Mains', 'GS1', 102, true),
  ('subj-mains-gs1-world', 'World History', 'Mains', 'GS1', 103, true),
  ('subj-mains-gs1-society', 'Indian Society', 'Mains', 'GS1', 104, true),
  ('subj-mains-gs1-geo', 'Geography', 'Mains', 'GS1', 105, true),
  ('subj-mains-gs2-const', 'Constitution', 'Mains', 'GS2', 201, true),
  ('subj-mains-gs2-gov', 'Polity & Governance', 'Mains', 'GS2', 202, true),
  ('subj-mains-gs2-socjus', 'Social Justice', 'Mains', 'GS2', 203, true),
  ('subj-mains-gs2-ir', 'International Relations', 'Mains', 'GS2', 204, true),
  ('subj-mains-gs3-eco', 'Economy', 'Mains', 'GS3', 301, true),
  ('subj-mains-gs3-agri', 'Agriculture', 'Mains', 'GS3', 302, true),
  ('subj-mains-gs3-scitech', 'Science & Technology', 'Mains', 'GS3', 303, true),
  ('subj-mains-gs3-env', 'Environment', 'Mains', 'GS3', 304, true),
  ('subj-mains-gs3-dm', 'Disaster Management', 'Mains', 'GS3', 305, true),
  ('subj-mains-gs3-sec', 'Internal Security', 'Mains', 'GS3', 306, true),
  ('subj-mains-gs4-ethics', 'Ethics, Integrity & Aptitude', 'Mains', 'GS4', 401, true),
  ('subj-mains-essay', 'Essay', 'Mains', 'Essay', 501, true),
  ('subj-mains-optional', 'Optional Subject', 'Mains', 'Optional', 601, true)
on conflict (id) do update set name = excluded.name, exam = excluded.exam, paper = excluded.paper, display_order = excluded.display_order;

-- 2. SEED SYLLABUS SECTIONS
insert into public.syllabus_sections (id, subject_id, name, display_order)
values
  ('sec-pre-hist-ancient', 'subj-pre-hist', 'Ancient India', 1),
  ('sec-pre-hist-medieval', 'subj-pre-hist', 'Medieval India', 2),
  ('sec-pre-hist-modern', 'subj-pre-hist', 'Modern Indian History & Freedom Struggle', 3),
  ('sec-pre-hist-postind', 'subj-pre-hist', 'Post-Independence India', 4),
  ('sec-pre-pol-const', 'subj-pre-polity', 'Constitutional Framework', 1),
  ('sec-pre-pol-union', 'subj-pre-polity', 'Union Executive & Parliament', 2),
  ('sec-pre-pol-judiciary', 'subj-pre-polity', 'Judiciary', 3),
  ('sec-pre-pol-state', 'subj-pre-polity', 'State Government & Administration', 4),
  ('sec-pre-pol-local', 'subj-pre-polity', 'Local Government', 5),
  ('sec-pre-pol-bodies', 'subj-pre-polity', 'Constitutional & Statutory Bodies', 6),
  ('sec-pre-pol-gov', 'subj-pre-polity', 'Governance & Civil Society', 7),
  ('sec-pre-geo-physical', 'subj-pre-geo', 'Physical Geography & Geomorphology', 1),
  ('sec-pre-geo-climate', 'subj-pre-geo', 'Climatology', 2),
  ('sec-pre-geo-ocean', 'subj-pre-geo', 'Oceanography', 3),
  ('sec-pre-geo-india', 'subj-pre-geo', 'Indian Geography', 4),
  ('sec-pre-geo-human-world', 'subj-pre-geo', 'Human, Economic & World Geography', 5),
  ('sec-pre-eco-concepts', 'subj-pre-eco', 'Basic Economic Concepts & National Income', 1),
  ('sec-pre-eco-monetary-fiscal', 'subj-pre-eco', 'Monetary & Fiscal Policy', 2),
  ('sec-pre-eco-external', 'subj-pre-eco', 'External Sector & Trade', 3),
  ('sec-pre-eco-growth-dev', 'subj-pre-eco', 'Economic Growth, Poverty & Inclusion', 4),
  ('sec-pre-eco-sectors', 'subj-pre-eco', 'Sectors & Economic Reforms', 5),
  ('sec-pre-env-ecology', 'subj-pre-env', 'Ecology & Ecosystems', 1),
  ('sec-pre-env-bio', 'subj-pre-env', 'Biodiversity & Conservation', 2),
  ('sec-pre-env-climate-poll', 'subj-pre-env', 'Climate Change & Pollution', 3),
  ('sec-pre-env-laws-conv', 'subj-pre-env', 'Environmental Laws & Conventions', 4),
  ('sec-pre-sci-basics', 'subj-pre-scitech', 'General Science Basics', 1),
  ('sec-pre-sci-biotech', 'subj-pre-scitech', 'Biotechnology & Genetics', 2),
  ('sec-pre-sci-space-def', 'subj-pre-scitech', 'Space, Defence & Nuclear Technology', 3),
  ('sec-pre-sci-it-emerging', 'subj-pre-scitech', 'IT & Emerging Technologies', 4),
  ('sec-pre-ca-cat', 'subj-pre-ca', 'Current Affairs Categories', 1),
  ('sec-pre-csat-rc', 'subj-pre-csat', 'Reading Comprehension', 1),
  ('sec-pre-csat-num', 'subj-pre-csat', 'Basic Numeracy & Data Interpretation', 2),
  ('sec-pre-csat-reasoning', 'subj-pre-csat', 'Reasoning & Problem Solving', 3),
  ('sec-mains-gs1-culture', 'subj-mains-gs1-culture', 'Art, Architecture & Cultural Traditions', 1),
  ('sec-mains-gs1-hist', 'subj-mains-gs1-history', 'British Rule & National Movement', 1),
  ('sec-mains-gs1-world', 'subj-mains-gs1-world', 'Major Events & Political Ideologies', 1),
  ('sec-mains-gs1-society', 'subj-mains-gs1-society', 'Social Structure, Diversity & Issues', 1),
  ('sec-mains-gs1-geo', 'subj-mains-gs1-geo', 'World & Indian Geography (Mains)', 1),
  ('sec-mains-gs2-const', 'subj-mains-gs2-const', 'Constitutional Framework & Organs', 1),
  ('sec-mains-gs2-gov', 'subj-mains-gs2-gov', 'Governance & Accountability', 1),
  ('sec-mains-gs2-socjus', 'subj-mains-gs2-socjus', 'Social Welfare & Human Development', 1),
  ('sec-mains-gs2-ir', 'subj-mains-gs2-ir', 'Foreign Policy & International Institutions', 1),
  ('sec-mains-gs3-eco', 'subj-mains-gs3-eco', 'Economic Growth & Public Finance', 1),
  ('sec-mains-gs3-agri', 'subj-mains-gs3-agri', 'Cropping, Tech & Food Security', 1),
  ('sec-mains-gs3-scitech', 'subj-mains-gs3-scitech', 'Technological Developments & Applications', 1),
  ('sec-mains-gs3-env', 'subj-mains-gs3-env', 'Ecology & Climate Action', 1),
  ('sec-mains-gs3-dm', 'subj-mains-gs3-dm', 'Disaster Preparedness & Response', 1),
  ('sec-mains-gs3-sec', 'subj-mains-gs3-sec', 'Security Challenges & Forces', 1),
  ('sec-mains-gs4-interface', 'subj-mains-gs4-ethics', 'Ethics & Human Interface', 1),
  ('sec-mains-gs4-thinkers', 'subj-mains-gs4-ethics', 'Thinkers', 2),
  ('sec-mains-gs4-pubadmin', 'subj-mains-gs4-ethics', 'Public Administration Ethics', 3),
  ('sec-mains-gs4-cases', 'subj-mains-gs4-ethics', 'Case Studies', 4),
  ('sec-mains-essay-themes', 'subj-mains-essay', 'Broad Essay Themes', 1),
  ('sec-mains-opt-paper1', 'subj-mains-optional', 'Paper I (Theory & Foundations)', 1),
  ('sec-mains-opt-paper2', 'subj-mains-optional', 'Paper II (Indian Context & Application)', 2)
on conflict (id) do update set name = excluded.name, subject_id = excluded.subject_id, display_order = excluded.display_order;

-- 3. SEED SYLLABUS TOPICS
insert into public.syllabus_topics (id, section_id, name, description, display_order, active)
values
  ('top-pre-hist-ancient-1-ancient-india-overview', 'sec-pre-hist-ancient', 'Ancient India Overview', '', 1, true),
  ('top-pre-hist-ancient-2-indus-valley-civilization', 'sec-pre-hist-ancient', 'Indus Valley Civilization', '', 2, true),
  ('top-pre-hist-ancient-3-vedic-period', 'sec-pre-hist-ancient', 'Vedic Period', '', 3, true),
  ('top-pre-hist-ancient-4-mahajanapadas', 'sec-pre-hist-ancient', 'Mahajanapadas', '', 4, true),
  ('top-pre-hist-ancient-5-buddhism', 'sec-pre-hist-ancient', 'Buddhism', '', 5, true),
  ('top-pre-hist-ancient-6-jainism', 'sec-pre-hist-ancient', 'Jainism', '', 6, true),
  ('top-pre-hist-ancient-7-mauryan-empire', 'sec-pre-hist-ancient', 'Mauryan Empire', '', 7, true),
  ('top-pre-hist-ancient-8-post-mauryan-india', 'sec-pre-hist-ancient', 'Post-Mauryan India', '', 8, true),
  ('top-pre-hist-ancient-9-gupta-period', 'sec-pre-hist-ancient', 'Gupta Period', '', 9, true),
  ('top-pre-hist-ancient-10-south-indian-kingdoms', 'sec-pre-hist-ancient', 'South Indian Kingdoms', '', 10, true),
  ('top-pre-hist-ancient-11-sangam-age', 'sec-pre-hist-ancient', 'Sangam Age', '', 11, true),
  ('top-pre-hist-medieval-1-medieval-india', 'sec-pre-hist-medieval', 'Medieval India', '', 1, true),
  ('top-pre-hist-medieval-2-delhi-sultanate', 'sec-pre-hist-medieval', 'Delhi Sultanate', '', 2, true),
  ('top-pre-hist-medieval-3-vijayanagara-empire', 'sec-pre-hist-medieval', 'Vijayanagara Empire', '', 3, true),
  ('top-pre-hist-medieval-4-mughal-empire', 'sec-pre-hist-medieval', 'Mughal Empire', '', 4, true),
  ('top-pre-hist-medieval-5-marathas', 'sec-pre-hist-medieval', 'Marathas', '', 5, true),
  ('top-pre-hist-medieval-6-bhakti-movement', 'sec-pre-hist-medieval', 'Bhakti Movement', '', 6, true),
  ('top-pre-hist-medieval-7-sufi-movement', 'sec-pre-hist-medieval', 'Sufi Movement', '', 7, true),
  ('top-pre-hist-modern-1-european-arrival-in-india', 'sec-pre-hist-modern', 'European Arrival in India', '', 1, true),
  ('top-pre-hist-modern-2-british-expansion', 'sec-pre-hist-modern', 'British Expansion', '', 2, true),
  ('top-pre-hist-modern-3-governor-generals-and-vicero', 'sec-pre-hist-modern', 'Governor-Generals and Viceroys', '', 3, true),
  ('top-pre-hist-modern-4-revolt-of-1857', 'sec-pre-hist-modern', 'Revolt of 1857', '', 4, true),
  ('top-pre-hist-modern-5-socio-religious-reform-movem', 'sec-pre-hist-modern', 'Socio-Religious Reform Movements', '', 5, true),
  ('top-pre-hist-modern-6-indian-national-congress', 'sec-pre-hist-modern', 'Indian National Congress', '', 6, true),
  ('top-pre-hist-modern-7-moderate-and-extremist-phase', 'sec-pre-hist-modern', 'Moderate and Extremist Phase', '', 7, true),
  ('top-pre-hist-modern-8-swadeshi-movement', 'sec-pre-hist-modern', 'Swadeshi Movement', '', 8, true),
  ('top-pre-hist-modern-9-home-rule-movement', 'sec-pre-hist-modern', 'Home Rule Movement', '', 9, true),
  ('top-pre-hist-modern-10-gandhian-era', 'sec-pre-hist-modern', 'Gandhian Era', '', 10, true),
  ('top-pre-hist-modern-11-non-cooperation-movement', 'sec-pre-hist-modern', 'Non-Cooperation Movement', '', 11, true),
  ('top-pre-hist-modern-12-civil-disobedience-movement', 'sec-pre-hist-modern', 'Civil Disobedience Movement', '', 12, true),
  ('top-pre-hist-modern-13-quit-india-movement', 'sec-pre-hist-modern', 'Quit India Movement', '', 13, true),
  ('top-pre-hist-modern-14-revolutionary-movement', 'sec-pre-hist-modern', 'Revolutionary Movement', '', 14, true),
  ('top-pre-hist-modern-15-constitutional-development', 'sec-pre-hist-modern', 'Constitutional Development', '', 15, true),
  ('top-pre-hist-modern-16-partition-and-independence', 'sec-pre-hist-modern', 'Partition and Independence', '', 16, true),
  ('top-pre-hist-postind-1-post-independence-india', 'sec-pre-hist-postind', 'Post-Independence India', '', 1, true),
  ('top-pre-hist-postind-2-reorganization-of-states', 'sec-pre-hist-postind', 'Reorganization of States', '', 2, true),
  ('top-pre-hist-postind-3-planning-and-democratic-con', 'sec-pre-hist-postind', 'Planning and Democratic Consolidation', '', 3, true),
  ('top-pre-hist-postind-4-major-developments-challeng', 'sec-pre-hist-postind', 'Major Developments & Challenges', '', 4, true),
  ('top-pre-pol-const-1-historical-background', 'sec-pre-pol-const', 'Historical Background', '', 1, true),
  ('top-pre-pol-const-2-constitution-making', 'sec-pre-pol-const', 'Constitution Making', '', 2, true),
  ('top-pre-pol-const-3-constitutional-features', 'sec-pre-pol-const', 'Constitutional Features', '', 3, true),
  ('top-pre-pol-const-4-preamble', 'sec-pre-pol-const', 'Preamble', '', 4, true),
  ('top-pre-pol-const-5-citizenship', 'sec-pre-pol-const', 'Citizenship', '', 5, true),
  ('top-pre-pol-const-6-fundamental-rights', 'sec-pre-pol-const', 'Fundamental Rights', '', 6, true),
  ('top-pre-pol-const-7-directive-principles', 'sec-pre-pol-const', 'Directive Principles', '', 7, true),
  ('top-pre-pol-const-8-fundamental-duties', 'sec-pre-pol-const', 'Fundamental Duties', '', 8, true),
  ('top-pre-pol-const-9-constitutional-amendments', 'sec-pre-pol-const', 'Constitutional Amendments', '', 9, true),
  ('top-pre-pol-const-10-basic-structure', 'sec-pre-pol-const', 'Basic Structure', '', 10, true),
  ('top-pre-pol-union-1-president', 'sec-pre-pol-union', 'President', '', 1, true),
  ('top-pre-pol-union-2-vice-president', 'sec-pre-pol-union', 'Vice President', '', 2, true),
  ('top-pre-pol-union-3-prime-minister', 'sec-pre-pol-union', 'Prime Minister', '', 3, true),
  ('top-pre-pol-union-4-council-of-ministers', 'sec-pre-pol-union', 'Council of Ministers', '', 4, true),
  ('top-pre-pol-union-5-parliament', 'sec-pre-pol-union', 'Parliament', '', 5, true),
  ('top-pre-pol-union-6-parliamentary-committees', 'sec-pre-pol-union', 'Parliamentary Committees', '', 6, true),
  ('top-pre-pol-judiciary-1-supreme-court', 'sec-pre-pol-judiciary', 'Supreme Court', '', 1, true),
  ('top-pre-pol-judiciary-2-high-courts', 'sec-pre-pol-judiciary', 'High Courts', '', 2, true),
  ('top-pre-pol-judiciary-3-judicial-review', 'sec-pre-pol-judiciary', 'Judicial Review', '', 3, true),
  ('top-pre-pol-judiciary-4-judicial-activism', 'sec-pre-pol-judiciary', 'Judicial Activism', '', 4, true),
  ('top-pre-pol-state-1-governor', 'sec-pre-pol-state', 'Governor', '', 1, true),
  ('top-pre-pol-state-2-chief-minister', 'sec-pre-pol-state', 'Chief Minister', '', 2, true),
  ('top-pre-pol-state-3-state-legislature', 'sec-pre-pol-state', 'State Legislature', '', 3, true),
  ('top-pre-pol-state-4-centre-state-relations', 'sec-pre-pol-state', 'Centre-State Relations', '', 4, true),
  ('top-pre-pol-state-5-inter-state-relations', 'sec-pre-pol-state', 'Inter-State Relations', '', 5, true),
  ('top-pre-pol-state-6-emergency-provisions', 'sec-pre-pol-state', 'Emergency Provisions', '', 6, true),
  ('top-pre-pol-local-1-local-government', 'sec-pre-pol-local', 'Local Government', '', 1, true),
  ('top-pre-pol-local-2-panchayati-raj', 'sec-pre-pol-local', 'Panchayati Raj', '', 2, true),
  ('top-pre-pol-local-3-municipalities', 'sec-pre-pol-local', 'Municipalities', '', 3, true),
  ('top-pre-pol-bodies-1-election-commission', 'sec-pre-pol-bodies', 'Election Commission', '', 1, true),
  ('top-pre-pol-bodies-2-upsc', 'sec-pre-pol-bodies', 'UPSC', '', 2, true),
  ('top-pre-pol-bodies-3-finance-commission', 'sec-pre-pol-bodies', 'Finance Commission', '', 3, true),
  ('top-pre-pol-bodies-4-cag', 'sec-pre-pol-bodies', 'CAG', '', 4, true),
  ('top-pre-pol-bodies-5-attorney-general', 'sec-pre-pol-bodies', 'Attorney General', '', 5, true),
  ('top-pre-pol-bodies-6-advocate-general', 'sec-pre-pol-bodies', 'Advocate General', '', 6, true),
  ('top-pre-pol-bodies-7-constitutional-bodies', 'sec-pre-pol-bodies', 'Constitutional Bodies', '', 7, true),
  ('top-pre-pol-bodies-8-statutory-bodies', 'sec-pre-pol-bodies', 'Statutory Bodies', '', 8, true),
  ('top-pre-pol-bodies-9-tribunals', 'sec-pre-pol-bodies', 'Tribunals', '', 9, true),
  ('top-pre-pol-gov-1-rti', 'sec-pre-pol-gov', 'RTI', '', 1, true),
  ('top-pre-pol-gov-2-governance', 'sec-pre-pol-gov', 'Governance', '', 2, true),
  ('top-pre-pol-gov-3-e-governance', 'sec-pre-pol-gov', 'E-Governance', '', 3, true),
  ('top-pre-pol-gov-4-pressure-groups', 'sec-pre-pol-gov', 'Pressure Groups', '', 4, true),
  ('top-pre-pol-gov-5-ngos', 'sec-pre-pol-gov', 'NGOs', '', 5, true),
  ('top-pre-pol-gov-6-civil-society', 'sec-pre-pol-gov', 'Civil Society', '', 6, true),
  ('top-pre-geo-physical-1-physical-geography', 'sec-pre-geo-physical', 'Physical Geography', '', 1, true),
  ('top-pre-geo-physical-2-earth-structure', 'sec-pre-geo-physical', 'Earth Structure', '', 2, true),
  ('top-pre-geo-physical-3-geomorphology', 'sec-pre-geo-physical', 'Geomorphology', '', 3, true),
  ('top-pre-geo-physical-4-plate-tectonics', 'sec-pre-geo-physical', 'Plate Tectonics', '', 4, true),
  ('top-pre-geo-physical-5-earthquakes', 'sec-pre-geo-physical', 'Earthquakes', '', 5, true),
  ('top-pre-geo-physical-6-volcanoes', 'sec-pre-geo-physical', 'Volcanoes', '', 6, true),
  ('top-pre-geo-physical-7-rocks', 'sec-pre-geo-physical', 'Rocks', '', 7, true),
  ('top-pre-geo-physical-8-landforms', 'sec-pre-geo-physical', 'Landforms', '', 8, true),
  ('top-pre-geo-climate-1-climatology', 'sec-pre-geo-climate', 'Climatology', '', 1, true),
  ('top-pre-geo-climate-2-atmosphere', 'sec-pre-geo-climate', 'Atmosphere', '', 2, true),
  ('top-pre-geo-climate-3-winds', 'sec-pre-geo-climate', 'Winds', '', 3, true),
  ('top-pre-geo-climate-4-pressure-belts', 'sec-pre-geo-climate', 'Pressure Belts', '', 4, true),
  ('top-pre-geo-climate-5-monsoons', 'sec-pre-geo-climate', 'Monsoons', '', 5, true),
  ('top-pre-geo-climate-6-cyclones', 'sec-pre-geo-climate', 'Cyclones', '', 6, true),
  ('top-pre-geo-ocean-1-oceanography', 'sec-pre-geo-ocean', 'Oceanography', '', 1, true),
  ('top-pre-geo-ocean-2-ocean-currents', 'sec-pre-geo-ocean', 'Ocean Currents', '', 2, true),
  ('top-pre-geo-ocean-3-tides', 'sec-pre-geo-ocean', 'Tides', '', 3, true),
  ('top-pre-geo-ocean-4-marine-resources', 'sec-pre-geo-ocean', 'Marine Resources', '', 4, true),
  ('top-pre-geo-india-1-indian-geography', 'sec-pre-geo-india', 'Indian Geography', '', 1, true),
  ('top-pre-geo-india-2-physiography-of-india', 'sec-pre-geo-india', 'Physiography of India', '', 2, true),
  ('top-pre-geo-india-3-rivers', 'sec-pre-geo-india', 'Rivers', '', 3, true),
  ('top-pre-geo-india-4-drainage-systems', 'sec-pre-geo-india', 'Drainage Systems', '', 4, true),
  ('top-pre-geo-india-5-climate-of-india', 'sec-pre-geo-india', 'Climate of India', '', 5, true),
  ('top-pre-geo-india-6-soils', 'sec-pre-geo-india', 'Soils', '', 6, true),
  ('top-pre-geo-india-7-natural-vegetation', 'sec-pre-geo-india', 'Natural Vegetation', '', 7, true),
  ('top-pre-geo-india-8-agriculture', 'sec-pre-geo-india', 'Agriculture', '', 8, true),
  ('top-pre-geo-india-9-minerals', 'sec-pre-geo-india', 'Minerals', '', 9, true),
  ('top-pre-geo-india-10-industries', 'sec-pre-geo-india', 'Industries', '', 10, true),
  ('top-pre-geo-india-11-transport', 'sec-pre-geo-india', 'Transport', '', 11, true),
  ('top-pre-geo-india-12-population', 'sec-pre-geo-india', 'Population', '', 12, true),
  ('top-pre-geo-india-13-urbanization', 'sec-pre-geo-india', 'Urbanization', '', 13, true),
  ('top-pre-geo-human-world-1-human-geography', 'sec-pre-geo-human-world', 'Human Geography', '', 1, true),
  ('top-pre-geo-human-world-2-economic-geography', 'sec-pre-geo-human-world', 'Economic Geography', '', 2, true),
  ('top-pre-geo-human-world-3-world-geography', 'sec-pre-geo-human-world', 'World Geography', '', 3, true),
  ('top-pre-geo-human-world-4-important-geographical-l', 'sec-pre-geo-human-world', 'Important Geographical Locations', '', 4, true),
  ('top-pre-geo-human-world-5-mapping', 'sec-pre-geo-human-world', 'Mapping', '', 5, true),
  ('top-pre-eco-concepts-1-basic-economic-concepts', 'sec-pre-eco-concepts', 'Basic Economic Concepts', '', 1, true),
  ('top-pre-eco-concepts-2-national-income', 'sec-pre-eco-concepts', 'National Income', '', 2, true),
  ('top-pre-eco-concepts-3-gdp-and-gnp', 'sec-pre-eco-concepts', 'GDP and GNP', '', 3, true),
  ('top-pre-eco-concepts-4-inflation', 'sec-pre-eco-concepts', 'Inflation', '', 4, true),
  ('top-pre-eco-monetary-fiscal-1-monetary-policy', 'sec-pre-eco-monetary-fiscal', 'Monetary Policy', '', 1, true),
  ('top-pre-eco-monetary-fiscal-2-fiscal-policy', 'sec-pre-eco-monetary-fiscal', 'Fiscal Policy', '', 2, true),
  ('top-pre-eco-monetary-fiscal-3-banking', 'sec-pre-eco-monetary-fiscal', 'Banking', '', 3, true),
  ('top-pre-eco-monetary-fiscal-4-rbi', 'sec-pre-eco-monetary-fiscal', 'RBI', '', 4, true),
  ('top-pre-eco-monetary-fiscal-5-financial-markets', 'sec-pre-eco-monetary-fiscal', 'Financial Markets', '', 5, true),
  ('top-pre-eco-monetary-fiscal-6-budget', 'sec-pre-eco-monetary-fiscal', 'Budget', '', 6, true),
  ('top-pre-eco-monetary-fiscal-7-taxation', 'sec-pre-eco-monetary-fiscal', 'Taxation', '', 7, true),
  ('top-pre-eco-monetary-fiscal-8-public-finance', 'sec-pre-eco-monetary-fiscal', 'Public Finance', '', 8, true),
  ('top-pre-eco-external-1-external-sector', 'sec-pre-eco-external', 'External Sector', '', 1, true),
  ('top-pre-eco-external-2-balance-of-payments', 'sec-pre-eco-external', 'Balance of Payments', '', 2, true),
  ('top-pre-eco-external-3-exchange-rates', 'sec-pre-eco-external', 'Exchange Rates', '', 3, true),
  ('top-pre-eco-external-4-international-trade', 'sec-pre-eco-external', 'International Trade', '', 4, true),
  ('top-pre-eco-growth-dev-1-economic-growth', 'sec-pre-eco-growth-dev', 'Economic Growth', '', 1, true),
  ('top-pre-eco-growth-dev-2-economic-development', 'sec-pre-eco-growth-dev', 'Economic Development', '', 2, true),
  ('top-pre-eco-growth-dev-3-poverty', 'sec-pre-eco-growth-dev', 'Poverty', '', 3, true),
  ('top-pre-eco-growth-dev-4-unemployment', 'sec-pre-eco-growth-dev', 'Unemployment', '', 4, true),
  ('top-pre-eco-growth-dev-5-inclusive-growth', 'sec-pre-eco-growth-dev', 'Inclusive Growth', '', 5, true),
  ('top-pre-eco-growth-dev-6-infrastructure', 'sec-pre-eco-growth-dev', 'Infrastructure', '', 6, true),
  ('top-pre-eco-growth-dev-7-financial-inclusion', 'sec-pre-eco-growth-dev', 'Financial Inclusion', '', 7, true),
  ('top-pre-eco-growth-dev-8-government-schemes', 'sec-pre-eco-growth-dev', 'Government Schemes', '', 8, true),
  ('top-pre-eco-sectors-1-agriculture', 'sec-pre-eco-sectors', 'Agriculture', '', 1, true),
  ('top-pre-eco-sectors-2-industry', 'sec-pre-eco-sectors', 'Industry', '', 2, true),
  ('top-pre-eco-sectors-3-services', 'sec-pre-eco-sectors', 'Services', '', 3, true),
  ('top-pre-eco-sectors-4-msmes', 'sec-pre-eco-sectors', 'MSMEs', '', 4, true),
  ('top-pre-eco-sectors-5-economic-reforms', 'sec-pre-eco-sectors', 'Economic Reforms', '', 5, true),
  ('top-pre-eco-sectors-6-liberalization', 'sec-pre-eco-sectors', 'Liberalization', '', 6, true),
  ('top-pre-eco-sectors-7-privatization', 'sec-pre-eco-sectors', 'Privatization', '', 7, true),
  ('top-pre-eco-sectors-8-globalization', 'sec-pre-eco-sectors', 'Globalization', '', 8, true),
  ('top-pre-env-ecology-1-ecology', 'sec-pre-env-ecology', 'Ecology', '', 1, true),
  ('top-pre-env-ecology-2-ecosystems', 'sec-pre-env-ecology', 'Ecosystems', '', 2, true),
  ('top-pre-env-ecology-3-food-chains', 'sec-pre-env-ecology', 'Food Chains', '', 3, true),
  ('top-pre-env-ecology-4-food-webs', 'sec-pre-env-ecology', 'Food Webs', '', 4, true),
  ('top-pre-env-ecology-5-ecological-pyramids', 'sec-pre-env-ecology', 'Ecological Pyramids', '', 5, true),
  ('top-pre-env-bio-1-biodiversity', 'sec-pre-env-bio', 'Biodiversity', '', 1, true),
  ('top-pre-env-bio-2-species', 'sec-pre-env-bio', 'Species', '', 2, true),
  ('top-pre-env-bio-3-protected-areas', 'sec-pre-env-bio', 'Protected Areas', '', 3, true),
  ('top-pre-env-bio-4-national-parks', 'sec-pre-env-bio', 'National Parks', '', 4, true),
  ('top-pre-env-bio-5-wildlife-sanctuaries', 'sec-pre-env-bio', 'Wildlife Sanctuaries', '', 5, true),
  ('top-pre-env-bio-6-biosphere-reserves', 'sec-pre-env-bio', 'Biosphere Reserves', '', 6, true),
  ('top-pre-env-bio-7-conservation', 'sec-pre-env-bio', 'Conservation', '', 7, true),
  ('top-pre-env-bio-8-forests', 'sec-pre-env-bio', 'Forests', '', 8, true),
  ('top-pre-env-bio-9-wetlands', 'sec-pre-env-bio', 'Wetlands', '', 9, true),
  ('top-pre-env-bio-10-marine-ecosystems', 'sec-pre-env-bio', 'Marine Ecosystems', '', 10, true),
  ('top-pre-env-climate-poll-1-climate-change', 'sec-pre-env-climate-poll', 'Climate Change', '', 1, true),
  ('top-pre-env-climate-poll-2-greenhouse-effect', 'sec-pre-env-climate-poll', 'Greenhouse Effect', '', 2, true),
  ('top-pre-env-climate-poll-3-global-warming', 'sec-pre-env-climate-poll', 'Global Warming', '', 3, true),
  ('top-pre-env-climate-poll-4-ozone-layer', 'sec-pre-env-climate-poll', 'Ozone Layer', '', 4, true),
  ('top-pre-env-climate-poll-5-pollution', 'sec-pre-env-climate-poll', 'Pollution', '', 5, true),
  ('top-pre-env-climate-poll-6-air-pollution', 'sec-pre-env-climate-poll', 'Air Pollution', '', 6, true),
  ('top-pre-env-climate-poll-7-water-pollution', 'sec-pre-env-climate-poll', 'Water Pollution', '', 7, true),
  ('top-pre-env-climate-poll-8-soil-pollution', 'sec-pre-env-climate-poll', 'Soil Pollution', '', 8, true),
  ('top-pre-env-climate-poll-9-waste-management', 'sec-pre-env-climate-poll', 'Waste Management', '', 9, true),
  ('top-pre-env-laws-conv-1-environmental-laws', 'sec-pre-env-laws-conv', 'Environmental Laws', '', 1, true),
  ('top-pre-env-laws-conv-2-environmental-organization', 'sec-pre-env-laws-conv', 'Environmental Organizations', '', 2, true),
  ('top-pre-env-laws-conv-3-international-environmenta', 'sec-pre-env-laws-conv', 'International Environmental Conventions', '', 3, true),
  ('top-pre-env-laws-conv-4-sustainable-development', 'sec-pre-env-laws-conv', 'Sustainable Development', '', 4, true),
  ('top-pre-env-laws-conv-5-renewable-energy', 'sec-pre-env-laws-conv', 'Renewable Energy', '', 5, true),
  ('top-pre-env-laws-conv-6-environmental-impact-asses', 'sec-pre-env-laws-conv', 'Environmental Impact Assessment', '', 6, true),
  ('top-pre-sci-basics-1-physics-basics', 'sec-pre-sci-basics', 'Physics Basics', '', 1, true),
  ('top-pre-sci-basics-2-chemistry-basics', 'sec-pre-sci-basics', 'Chemistry Basics', '', 2, true),
  ('top-pre-sci-basics-3-biology-basics', 'sec-pre-sci-basics', 'Biology Basics', '', 3, true),
  ('top-pre-sci-basics-4-human-biology', 'sec-pre-sci-basics', 'Human Biology', '', 4, true),
  ('top-pre-sci-basics-5-diseases', 'sec-pre-sci-basics', 'Diseases', '', 5, true),
  ('top-pre-sci-biotech-1-biotechnology', 'sec-pre-sci-biotech', 'Biotechnology', '', 1, true),
  ('top-pre-sci-biotech-2-genetics', 'sec-pre-sci-biotech', 'Genetics', '', 2, true),
  ('top-pre-sci-biotech-3-biotechnology-applications', 'sec-pre-sci-biotech', 'Biotechnology Applications', '', 3, true),
  ('top-pre-sci-space-def-1-space-technology', 'sec-pre-sci-space-def', 'Space Technology', '', 1, true),
  ('top-pre-sci-space-def-2-satellites', 'sec-pre-sci-space-def', 'Satellites', '', 2, true),
  ('top-pre-sci-space-def-3-isro', 'sec-pre-sci-space-def', 'ISRO', '', 3, true),
  ('top-pre-sci-space-def-4-defence-technology', 'sec-pre-sci-space-def', 'Defence Technology', '', 4, true),
  ('top-pre-sci-space-def-5-nuclear-technology', 'sec-pre-sci-space-def', 'Nuclear Technology', '', 5, true),
  ('top-pre-sci-it-emerging-1-nanotechnology', 'sec-pre-sci-it-emerging', 'Nanotechnology', '', 1, true),
  ('top-pre-sci-it-emerging-2-artificial-intelligence', 'sec-pre-sci-it-emerging', 'Artificial Intelligence', '', 2, true),
  ('top-pre-sci-it-emerging-3-robotics', 'sec-pre-sci-it-emerging', 'Robotics', '', 3, true),
  ('top-pre-sci-it-emerging-4-information-technology', 'sec-pre-sci-it-emerging', 'Information Technology', '', 4, true),
  ('top-pre-sci-it-emerging-5-communication-technology', 'sec-pre-sci-it-emerging', 'Communication Technology', '', 5, true),
  ('top-pre-sci-it-emerging-6-semiconductor-technology', 'sec-pre-sci-it-emerging', 'Semiconductor Technology', '', 6, true),
  ('top-pre-sci-it-emerging-7-emerging-technologies', 'sec-pre-sci-it-emerging', 'Emerging Technologies', '', 7, true),
  ('top-pre-ca-cat-1-national', 'sec-pre-ca-cat', 'National', '', 1, true),
  ('top-pre-ca-cat-2-international', 'sec-pre-ca-cat', 'International', '', 2, true),
  ('top-pre-ca-cat-3-economy', 'sec-pre-ca-cat', 'Economy', '', 3, true),
  ('top-pre-ca-cat-4-polity', 'sec-pre-ca-cat', 'Polity', '', 4, true),
  ('top-pre-ca-cat-5-environment', 'sec-pre-ca-cat', 'Environment', '', 5, true),
  ('top-pre-ca-cat-6-science-technology', 'sec-pre-ca-cat', 'Science & Technology', '', 6, true),
  ('top-pre-ca-cat-7-defence', 'sec-pre-ca-cat', 'Defence', '', 7, true),
  ('top-pre-ca-cat-8-government-schemes', 'sec-pre-ca-cat', 'Government Schemes', '', 8, true),
  ('top-pre-ca-cat-9-reports-indices', 'sec-pre-ca-cat', 'Reports & Indices', '', 9, true),
  ('top-pre-ca-cat-10-awards', 'sec-pre-ca-cat', 'Awards', '', 10, true),
  ('top-pre-ca-cat-11-important-personalities', 'sec-pre-ca-cat', 'Important Personalities', '', 11, true),
  ('top-pre-ca-cat-12-places-in-news', 'sec-pre-ca-cat', 'Places in News', '', 12, true),
  ('top-pre-ca-cat-13-international-organizations', 'sec-pre-ca-cat', 'International Organizations', '', 13, true),
  ('top-pre-csat-rc-1-reading-comprehension', 'sec-pre-csat-rc', 'Reading Comprehension', '', 1, true),
  ('top-pre-csat-num-1-basic-numeracy', 'sec-pre-csat-num', 'Basic Numeracy', '', 1, true),
  ('top-pre-csat-num-2-number-system', 'sec-pre-csat-num', 'Number System', '', 2, true),
  ('top-pre-csat-num-3-percentage', 'sec-pre-csat-num', 'Percentage', '', 3, true),
  ('top-pre-csat-num-4-profit-loss', 'sec-pre-csat-num', 'Profit & Loss', '', 4, true),
  ('top-pre-csat-num-5-ratio-proportion', 'sec-pre-csat-num', 'Ratio & Proportion', '', 5, true),
  ('top-pre-csat-num-6-average', 'sec-pre-csat-num', 'Average', '', 6, true),
  ('top-pre-csat-num-7-time-work', 'sec-pre-csat-num', 'Time & Work', '', 7, true),
  ('top-pre-csat-num-8-time-speed-distance', 'sec-pre-csat-num', 'Time Speed Distance', '', 8, true),
  ('top-pre-csat-num-9-simple-compound-interest', 'sec-pre-csat-num', 'Simple & Compound Interest', '', 9, true),
  ('top-pre-csat-num-10-data-interpretation', 'sec-pre-csat-num', 'Data Interpretation', '', 10, true),
  ('top-pre-csat-num-11-data-sufficiency', 'sec-pre-csat-num', 'Data Sufficiency', '', 11, true),
  ('top-pre-csat-reasoning-1-logical-reasoning', 'sec-pre-csat-reasoning', 'Logical Reasoning', '', 1, true),
  ('top-pre-csat-reasoning-2-analytical-ability', 'sec-pre-csat-reasoning', 'Analytical Ability', '', 2, true),
  ('top-pre-csat-reasoning-3-decision-making', 'sec-pre-csat-reasoning', 'Decision Making', '', 3, true),
  ('top-pre-csat-reasoning-4-problem-solving', 'sec-pre-csat-reasoning', 'Problem Solving', '', 4, true),
  ('top-mains-gs1-culture-1-architecture', 'sec-mains-gs1-culture', 'Architecture', '', 1, true),
  ('top-mains-gs1-culture-2-sculpture', 'sec-mains-gs1-culture', 'Sculpture', '', 2, true),
  ('top-mains-gs1-culture-3-paintings', 'sec-mains-gs1-culture', 'Paintings', '', 3, true),
  ('top-mains-gs1-culture-4-literature', 'sec-mains-gs1-culture', 'Literature', '', 4, true),
  ('top-mains-gs1-culture-5-music', 'sec-mains-gs1-culture', 'Music', '', 5, true),
  ('top-mains-gs1-culture-6-dance', 'sec-mains-gs1-culture', 'Dance', '', 6, true),
  ('top-mains-gs1-culture-7-theatre', 'sec-mains-gs1-culture', 'Theatre', '', 7, true),
  ('top-mains-gs1-culture-8-religion-and-philosophy', 'sec-mains-gs1-culture', 'Religion and Philosophy', '', 8, true),
  ('top-mains-gs1-culture-9-cultural-traditions', 'sec-mains-gs1-culture', 'Cultural Traditions', '', 9, true),
  ('top-mains-gs1-culture-10-unesco-heritage', 'sec-mains-gs1-culture', 'UNESCO Heritage', '', 10, true),
  ('top-mains-gs1-hist-1-british-rule', 'sec-mains-gs1-hist', 'British Rule', '', 1, true),
  ('top-mains-gs1-hist-2-economic-impact-of-british-ru', 'sec-mains-gs1-hist', 'Economic Impact of British Rule', '', 2, true),
  ('top-mains-gs1-hist-3-revolt-of-1857', 'sec-mains-gs1-hist', 'Revolt of 1857', '', 3, true),
  ('top-mains-gs1-hist-4-social-reform', 'sec-mains-gs1-hist', 'Social Reform', '', 4, true),
  ('top-mains-gs1-hist-5-national-movement', 'sec-mains-gs1-hist', 'National Movement', '', 5, true),
  ('top-mains-gs1-hist-6-gandhian-era', 'sec-mains-gs1-hist', 'Gandhian Era', '', 6, true),
  ('top-mains-gs1-hist-7-revolutionary-movement', 'sec-mains-gs1-hist', 'Revolutionary Movement', '', 7, true),
  ('top-mains-gs1-hist-8-constitutional-development', 'sec-mains-gs1-hist', 'Constitutional Development', '', 8, true),
  ('top-mains-gs1-hist-9-independence-and-partition', 'sec-mains-gs1-hist', 'Independence and Partition', '', 9, true),
  ('top-mains-gs1-world-1-renaissance', 'sec-mains-gs1-world', 'Renaissance', '', 1, true),
  ('top-mains-gs1-world-2-reformation', 'sec-mains-gs1-world', 'Reformation', '', 2, true),
  ('top-mains-gs1-world-3-enlightenment', 'sec-mains-gs1-world', 'Enlightenment', '', 3, true),
  ('top-mains-gs1-world-4-american-revolution', 'sec-mains-gs1-world', 'American Revolution', '', 4, true),
  ('top-mains-gs1-world-5-french-revolution', 'sec-mains-gs1-world', 'French Revolution', '', 5, true),
  ('top-mains-gs1-world-6-industrial-revolution', 'sec-mains-gs1-world', 'Industrial Revolution', '', 6, true),
  ('top-mains-gs1-world-7-nationalism', 'sec-mains-gs1-world', 'Nationalism', '', 7, true),
  ('top-mains-gs1-world-8-unification-of-europe', 'sec-mains-gs1-world', 'Unification of Europe', '', 8, true),
  ('top-mains-gs1-world-9-unification-of-germany', 'sec-mains-gs1-world', 'Unification of Germany', '', 9, true),
  ('top-mains-gs1-world-10-unification-of-italy', 'sec-mains-gs1-world', 'Unification of Italy', '', 10, true),
  ('top-mains-gs1-world-11-imperialism', 'sec-mains-gs1-world', 'Imperialism', '', 11, true),
  ('top-mains-gs1-world-12-colonialism', 'sec-mains-gs1-world', 'Colonialism', '', 12, true),
  ('top-mains-gs1-world-13-world-war-i', 'sec-mains-gs1-world', 'World War I', '', 13, true),
  ('top-mains-gs1-world-14-russian-revolution', 'sec-mains-gs1-world', 'Russian Revolution', '', 14, true),
  ('top-mains-gs1-world-15-world-war-ii', 'sec-mains-gs1-world', 'World War II', '', 15, true),
  ('top-mains-gs1-world-16-decolonization', 'sec-mains-gs1-world', 'Decolonization', '', 16, true),
  ('top-mains-gs1-world-17-cold-war', 'sec-mains-gs1-world', 'Cold War', '', 17, true),
  ('top-mains-gs1-world-18-political-ideologies', 'sec-mains-gs1-world', 'Political Ideologies', '', 18, true),
  ('top-mains-gs1-society-1-salient-features', 'sec-mains-gs1-society', 'Salient Features', '', 1, true),
  ('top-mains-gs1-society-2-diversity', 'sec-mains-gs1-society', 'Diversity', '', 2, true),
  ('top-mains-gs1-society-3-women', 'sec-mains-gs1-society', 'Women', '', 3, true),
  ('top-mains-gs1-society-4-population', 'sec-mains-gs1-society', 'Population', '', 4, true),
  ('top-mains-gs1-society-5-poverty', 'sec-mains-gs1-society', 'Poverty', '', 5, true),
  ('top-mains-gs1-society-6-urbanization', 'sec-mains-gs1-society', 'Urbanization', '', 6, true),
  ('top-mains-gs1-society-7-globalization', 'sec-mains-gs1-society', 'Globalization', '', 7, true),
  ('top-mains-gs1-society-8-communalism', 'sec-mains-gs1-society', 'Communalism', '', 8, true),
  ('top-mains-gs1-society-9-regionalism', 'sec-mains-gs1-society', 'Regionalism', '', 9, true),
  ('top-mains-gs1-society-10-secularism', 'sec-mains-gs1-society', 'Secularism', '', 10, true),
  ('top-mains-gs1-society-11-social-empowerment', 'sec-mains-gs1-society', 'Social Empowerment', '', 11, true),
  ('top-mains-gs1-society-12-social-issues', 'sec-mains-gs1-society', 'Social Issues', '', 12, true),
  ('top-mains-gs1-geo-1-distribution-of-key-natural-re', 'sec-mains-gs1-geo', 'Distribution of Key Natural Resources', '', 1, true),
  ('top-mains-gs1-geo-2-factors-responsible-for-locati', 'sec-mains-gs1-geo', 'Factors Responsible for Location of Industries', '', 2, true),
  ('top-mains-gs1-geo-3-important-geophysical-phenomen', 'sec-mains-gs1-geo', 'Important Geophysical Phenomena', '', 3, true),
  ('top-mains-gs1-geo-4-geographical-features-and-envi', 'sec-mains-gs1-geo', 'Geographical Features and Environmental Changes', '', 4, true),
  ('top-mains-gs2-const-1-constitutional-framework', 'sec-mains-gs2-const', 'Constitutional Framework', '', 1, true),
  ('top-mains-gs2-const-2-constitutional-amendments', 'sec-mains-gs2-const', 'Constitutional Amendments', '', 2, true),
  ('top-mains-gs2-const-3-federalism', 'sec-mains-gs2-const', 'Federalism', '', 3, true),
  ('top-mains-gs2-const-4-separation-of-powers', 'sec-mains-gs2-const', 'Separation of Powers', '', 4, true),
  ('top-mains-gs2-const-5-parliament', 'sec-mains-gs2-const', 'Parliament', '', 5, true),
  ('top-mains-gs2-const-6-judiciary', 'sec-mains-gs2-const', 'Judiciary', '', 6, true),
  ('top-mains-gs2-const-7-executive', 'sec-mains-gs2-const', 'Executive', '', 7, true),
  ('top-mains-gs2-const-8-constitutional-bodies', 'sec-mains-gs2-const', 'Constitutional Bodies', '', 8, true),
  ('top-mains-gs2-gov-1-parliament', 'sec-mains-gs2-gov', 'Parliament', '', 1, true),
  ('top-mains-gs2-gov-2-executive', 'sec-mains-gs2-gov', 'Executive', '', 2, true),
  ('top-mains-gs2-gov-3-judiciary', 'sec-mains-gs2-gov', 'Judiciary', '', 3, true),
  ('top-mains-gs2-gov-4-elections', 'sec-mains-gs2-gov', 'Elections', '', 4, true),
  ('top-mains-gs2-gov-5-governance', 'sec-mains-gs2-gov', 'Governance', '', 5, true),
  ('top-mains-gs2-gov-6-transparency', 'sec-mains-gs2-gov', 'Transparency', '', 6, true),
  ('top-mains-gs2-gov-7-accountability', 'sec-mains-gs2-gov', 'Accountability', '', 7, true),
  ('top-mains-gs2-gov-8-e-governance', 'sec-mains-gs2-gov', 'E-Governance', '', 8, true),
  ('top-mains-gs2-gov-9-civil-services', 'sec-mains-gs2-gov', 'Civil Services', '', 9, true),
  ('top-mains-gs2-gov-10-ngos', 'sec-mains-gs2-gov', 'NGOs', '', 10, true),
  ('top-mains-gs2-gov-11-pressure-groups', 'sec-mains-gs2-gov', 'Pressure Groups', '', 11, true),
  ('top-mains-gs2-gov-12-citizen-charters', 'sec-mains-gs2-gov', 'Citizen Charters', '', 12, true),
  ('top-mains-gs2-socjus-1-health', 'sec-mains-gs2-socjus', 'Health', '', 1, true),
  ('top-mains-gs2-socjus-2-education', 'sec-mains-gs2-socjus', 'Education', '', 2, true),
  ('top-mains-gs2-socjus-3-poverty', 'sec-mains-gs2-socjus', 'Poverty', '', 3, true),
  ('top-mains-gs2-socjus-4-hunger', 'sec-mains-gs2-socjus', 'Hunger', '', 4, true),
  ('top-mains-gs2-socjus-5-vulnerable-sections', 'sec-mains-gs2-socjus', 'Vulnerable Sections', '', 5, true),
  ('top-mains-gs2-socjus-6-welfare-schemes', 'sec-mains-gs2-socjus', 'Welfare Schemes', '', 6, true),
  ('top-mains-gs2-socjus-7-social-sector', 'sec-mains-gs2-socjus', 'Social Sector', '', 7, true),
  ('top-mains-gs2-socjus-8-human-development', 'sec-mains-gs2-socjus', 'Human Development', '', 8, true),
  ('top-mains-gs2-ir-1-india-and-neighbours', 'sec-mains-gs2-ir', 'India and Neighbours', '', 1, true),
  ('top-mains-gs2-ir-2-india-and-major-powers', 'sec-mains-gs2-ir', 'India and Major Powers', '', 2, true),
  ('top-mains-gs2-ir-3-regional-organizations', 'sec-mains-gs2-ir', 'Regional Organizations', '', 3, true),
  ('top-mains-gs2-ir-4-international-organizations', 'sec-mains-gs2-ir', 'International Organizations', '', 4, true),
  ('top-mains-gs2-ir-5-united-nations', 'sec-mains-gs2-ir', 'United Nations', '', 5, true),
  ('top-mains-gs2-ir-6-wto', 'sec-mains-gs2-ir', 'WTO', '', 6, true),
  ('top-mains-gs2-ir-7-imf', 'sec-mains-gs2-ir', 'IMF', '', 7, true),
  ('top-mains-gs2-ir-8-world-bank', 'sec-mains-gs2-ir', 'World Bank', '', 8, true),
  ('top-mains-gs2-ir-9-bilateral-relations', 'sec-mains-gs2-ir', 'Bilateral Relations', '', 9, true),
  ('top-mains-gs2-ir-10-multilateral-relations', 'sec-mains-gs2-ir', 'Multilateral Relations', '', 10, true),
  ('top-mains-gs2-ir-11-global-issues', 'sec-mains-gs2-ir', 'Global Issues', '', 11, true),
  ('top-mains-gs2-ir-12-indian-diaspora', 'sec-mains-gs2-ir', 'Indian Diaspora', '', 12, true),
  ('top-mains-gs3-eco-1-growth', 'sec-mains-gs3-eco', 'Growth', '', 1, true),
  ('top-mains-gs3-eco-2-development', 'sec-mains-gs3-eco', 'Development', '', 2, true),
  ('top-mains-gs3-eco-3-employment', 'sec-mains-gs3-eco', 'Employment', '', 3, true),
  ('top-mains-gs3-eco-4-inclusive-growth', 'sec-mains-gs3-eco', 'Inclusive Growth', '', 4, true),
  ('top-mains-gs3-eco-5-budget', 'sec-mains-gs3-eco', 'Budget', '', 5, true),
  ('top-mains-gs3-eco-6-taxation', 'sec-mains-gs3-eco', 'Taxation', '', 6, true),
  ('top-mains-gs3-eco-7-infrastructure', 'sec-mains-gs3-eco', 'Infrastructure', '', 7, true),
  ('top-mains-gs3-eco-8-investment', 'sec-mains-gs3-eco', 'Investment', '', 8, true),
  ('top-mains-gs3-eco-9-banking', 'sec-mains-gs3-eco', 'Banking', '', 9, true),
  ('top-mains-gs3-eco-10-financial-markets', 'sec-mains-gs3-eco', 'Financial Markets', '', 10, true),
  ('top-mains-gs3-agri-1-cropping-patterns', 'sec-mains-gs3-agri', 'Cropping Patterns', '', 1, true),
  ('top-mains-gs3-agri-2-irrigation', 'sec-mains-gs3-agri', 'Irrigation', '', 2, true),
  ('top-mains-gs3-agri-3-agricultural-marketing', 'sec-mains-gs3-agri', 'Agricultural Marketing', '', 3, true),
  ('top-mains-gs3-agri-4-msp', 'sec-mains-gs3-agri', 'MSP', '', 4, true),
  ('top-mains-gs3-agri-5-food-processing', 'sec-mains-gs3-agri', 'Food Processing', '', 5, true),
  ('top-mains-gs3-agri-6-land-reforms', 'sec-mains-gs3-agri', 'Land Reforms', '', 6, true),
  ('top-mains-gs3-agri-7-subsidies', 'sec-mains-gs3-agri', 'Subsidies', '', 7, true),
  ('top-mains-gs3-agri-8-agricultural-technology', 'sec-mains-gs3-agri', 'Agricultural Technology', '', 8, true),
  ('top-mains-gs3-agri-9-animal-husbandry', 'sec-mains-gs3-agri', 'Animal Husbandry', '', 9, true),
  ('top-mains-gs3-agri-10-fisheries', 'sec-mains-gs3-agri', 'Fisheries', '', 10, true),
  ('top-mains-gs3-agri-11-food-security', 'sec-mains-gs3-agri', 'Food Security', '', 11, true),
  ('top-mains-gs3-scitech-1-space', 'sec-mains-gs3-scitech', 'Space', '', 1, true),
  ('top-mains-gs3-scitech-2-biotechnology', 'sec-mains-gs3-scitech', 'Biotechnology', '', 2, true),
  ('top-mains-gs3-scitech-3-nanotechnology', 'sec-mains-gs3-scitech', 'Nanotechnology', '', 3, true),
  ('top-mains-gs3-scitech-4-ai', 'sec-mains-gs3-scitech', 'AI', '', 4, true),
  ('top-mains-gs3-scitech-5-robotics', 'sec-mains-gs3-scitech', 'Robotics', '', 5, true),
  ('top-mains-gs3-scitech-6-defence-technology', 'sec-mains-gs3-scitech', 'Defence Technology', '', 6, true),
  ('top-mains-gs3-scitech-7-cyber-technology', 'sec-mains-gs3-scitech', 'Cyber Technology', '', 7, true),
  ('top-mains-gs3-scitech-8-emerging-technologies', 'sec-mains-gs3-scitech', 'Emerging Technologies', '', 8, true),
  ('top-mains-gs3-env-1-biodiversity', 'sec-mains-gs3-env', 'Biodiversity', '', 1, true),
  ('top-mains-gs3-env-2-conservation', 'sec-mains-gs3-env', 'Conservation', '', 2, true),
  ('top-mains-gs3-env-3-climate-change', 'sec-mains-gs3-env', 'Climate Change', '', 3, true),
  ('top-mains-gs3-env-4-pollution', 'sec-mains-gs3-env', 'Pollution', '', 4, true),
  ('top-mains-gs3-env-5-environmental-governance', 'sec-mains-gs3-env', 'Environmental Governance', '', 5, true),
  ('top-mains-gs3-env-6-renewable-energy', 'sec-mains-gs3-env', 'Renewable Energy', '', 6, true),
  ('top-mains-gs3-env-7-sustainable-development', 'sec-mains-gs3-env', 'Sustainable Development', '', 7, true),
  ('top-mains-gs3-dm-1-disaster-types', 'sec-mains-gs3-dm', 'Disaster Types', '', 1, true),
  ('top-mains-gs3-dm-2-disaster-preparedness', 'sec-mains-gs3-dm', 'Disaster Preparedness', '', 2, true),
  ('top-mains-gs3-dm-3-mitigation', 'sec-mains-gs3-dm', 'Mitigation', '', 3, true),
  ('top-mains-gs3-dm-4-response', 'sec-mains-gs3-dm', 'Response', '', 4, true),
  ('top-mains-gs3-dm-5-recovery', 'sec-mains-gs3-dm', 'Recovery', '', 5, true),
  ('top-mains-gs3-dm-6-institutional-framework', 'sec-mains-gs3-dm', 'Institutional Framework', '', 6, true),
  ('top-mains-gs3-dm-7-ndma', 'sec-mains-gs3-dm', 'NDMA', '', 7, true),
  ('top-mains-gs3-dm-8-sendai-framework', 'sec-mains-gs3-dm', 'Sendai Framework', '', 8, true),
  ('top-mains-gs3-sec-1-terrorism', 'sec-mains-gs3-sec', 'Terrorism', '', 1, true),
  ('top-mains-gs3-sec-2-extremism', 'sec-mains-gs3-sec', 'Extremism', '', 2, true),
  ('top-mains-gs3-sec-3-insurgency', 'sec-mains-gs3-sec', 'Insurgency', '', 3, true),
  ('top-mains-gs3-sec-4-cyber-security', 'sec-mains-gs3-sec', 'Cyber Security', '', 4, true),
  ('top-mains-gs3-sec-5-money-laundering', 'sec-mains-gs3-sec', 'Money Laundering', '', 5, true),
  ('top-mains-gs3-sec-6-border-management', 'sec-mains-gs3-sec', 'Border Management', '', 6, true),
  ('top-mains-gs3-sec-7-organized-crime', 'sec-mains-gs3-sec', 'Organized Crime', '', 7, true),
  ('top-mains-gs3-sec-8-security-forces', 'sec-mains-gs3-sec', 'Security Forces', '', 8, true),
  ('top-mains-gs3-sec-9-maritime-security', 'sec-mains-gs3-sec', 'Maritime Security', '', 9, true),
  ('top-mains-gs4-interface-1-ethics', 'sec-mains-gs4-interface', 'Ethics', '', 1, true),
  ('top-mains-gs4-interface-2-morality', 'sec-mains-gs4-interface', 'Morality', '', 2, true),
  ('top-mains-gs4-interface-3-human-values', 'sec-mains-gs4-interface', 'Human Values', '', 3, true),
  ('top-mains-gs4-interface-4-ethical-dilemmas', 'sec-mains-gs4-interface', 'Ethical Dilemmas', '', 4, true),
  ('top-mains-gs4-interface-5-attitude', 'sec-mains-gs4-interface', 'Attitude', '', 5, true),
  ('top-mains-gs4-interface-6-emotional-intelligence', 'sec-mains-gs4-interface', 'Emotional Intelligence', '', 6, true),
  ('top-mains-gs4-thinkers-1-indian-thinkers', 'sec-mains-gs4-thinkers', 'Indian Thinkers', '', 1, true),
  ('top-mains-gs4-thinkers-2-western-thinkers', 'sec-mains-gs4-thinkers', 'Western Thinkers', '', 2, true),
  ('top-mains-gs4-thinkers-3-philosophical-ideas', 'sec-mains-gs4-thinkers', 'Philosophical Ideas', '', 3, true),
  ('top-mains-gs4-pubadmin-1-integrity', 'sec-mains-gs4-pubadmin', 'Integrity', '', 1, true),
  ('top-mains-gs4-pubadmin-2-impartiality', 'sec-mains-gs4-pubadmin', 'Impartiality', '', 2, true),
  ('top-mains-gs4-pubadmin-3-objectivity', 'sec-mains-gs4-pubadmin', 'Objectivity', '', 3, true),
  ('top-mains-gs4-pubadmin-4-accountability', 'sec-mains-gs4-pubadmin', 'Accountability', '', 4, true),
  ('top-mains-gs4-pubadmin-5-transparency', 'sec-mains-gs4-pubadmin', 'Transparency', '', 5, true),
  ('top-mains-gs4-pubadmin-6-code-of-conduct', 'sec-mains-gs4-pubadmin', 'Code of Conduct', '', 6, true),
  ('top-mains-gs4-pubadmin-7-code-of-ethics', 'sec-mains-gs4-pubadmin', 'Code of Ethics', '', 7, true),
  ('top-mains-gs4-pubadmin-8-corruption', 'sec-mains-gs4-pubadmin', 'Corruption', '', 8, true),
  ('top-mains-gs4-pubadmin-9-probity', 'sec-mains-gs4-pubadmin', 'Probity', '', 9, true),
  ('top-mains-gs4-cases-1-ethical-dilemmas', 'sec-mains-gs4-cases', 'Ethical Dilemmas', '', 1, true),
  ('top-mains-gs4-cases-2-administrative-cases', 'sec-mains-gs4-cases', 'Administrative Cases', '', 2, true),
  ('top-mains-gs4-cases-3-conflict-of-interest', 'sec-mains-gs4-cases', 'Conflict of Interest', '', 3, true),
  ('top-mains-gs4-cases-4-public-service-values', 'sec-mains-gs4-cases', 'Public Service Values', '', 4, true),
  ('top-mains-gs4-cases-5-decision-making', 'sec-mains-gs4-cases', 'Decision Making', '', 5, true),
  ('top-mains-essay-themes-1-society', 'sec-mains-essay-themes', 'Society', '', 1, true),
  ('top-mains-essay-themes-2-economy', 'sec-mains-essay-themes', 'Economy', '', 2, true),
  ('top-mains-essay-themes-3-governance', 'sec-mains-essay-themes', 'Governance', '', 3, true),
  ('top-mains-essay-themes-4-politics', 'sec-mains-essay-themes', 'Politics', '', 4, true),
  ('top-mains-essay-themes-5-philosophy', 'sec-mains-essay-themes', 'Philosophy', '', 5, true),
  ('top-mains-essay-themes-6-ethics', 'sec-mains-essay-themes', 'Ethics', '', 6, true),
  ('top-mains-essay-themes-7-science-technology', 'sec-mains-essay-themes', 'Science & Technology', '', 7, true),
  ('top-mains-essay-themes-8-environment', 'sec-mains-essay-themes', 'Environment', '', 8, true),
  ('top-mains-essay-themes-9-education', 'sec-mains-essay-themes', 'Education', '', 9, true),
  ('top-mains-essay-themes-10-women', 'sec-mains-essay-themes', 'Women', '', 10, true),
  ('top-mains-essay-themes-11-international-relations', 'sec-mains-essay-themes', 'International Relations', '', 11, true),
  ('top-mains-essay-themes-12-democracy', 'sec-mains-essay-themes', 'Democracy', '', 12, true),
  ('top-mains-essay-themes-13-development', 'sec-mains-essay-themes', 'Development', '', 13, true),
  ('top-mains-essay-themes-14-social-issues', 'sec-mains-essay-themes', 'Social Issues', '', 14, true),
  ('top-mains-opt-paper1-1-foundations-core-concepts', 'sec-mains-opt-paper1', 'Foundations & Core Concepts', '', 1, true),
  ('top-mains-opt-paper1-2-advanced-theories-models', 'sec-mains-opt-paper1', 'Advanced Theories & Models', '', 2, true),
  ('top-mains-opt-paper1-3-thinkers-major-contribution', 'sec-mains-opt-paper1', 'Thinkers & Major Contributions', '', 3, true),
  ('top-mains-opt-paper1-4-applied-approaches-methods', 'sec-mains-opt-paper1', 'Applied Approaches & Methods', '', 4, true),
  ('top-mains-opt-paper2-1-historical-institutional-ev', 'sec-mains-opt-paper2', 'Historical & Institutional Evolution', '', 1, true),
  ('top-mains-opt-paper2-2-indian-perspective-dimensio', 'sec-mains-opt-paper2', 'Indian Perspective & Dimensions', '', 2, true),
  ('top-mains-opt-paper2-3-contemporary-policies-issue', 'sec-mains-opt-paper2', 'Contemporary Policies & Issues', '', 3, true),
  ('top-mains-opt-paper2-4-case-studies-empirical-anal', 'sec-mains-opt-paper2', 'Case Studies & Empirical Analysis', '', 4, true)
on conflict (id) do update set name = excluded.name, section_id = excluded.section_id, display_order = excluded.display_order;
